name: Build
on: [push]
jobs:
  build:
    name: Ubuntu->Windows Cross Compile
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v1
    - name: Install deps
      run: sudo apt install gcc-mingw-w64-x86-64
    - name: Build
      run: CC=x86_64-w64-mingw32-gcc make
    - name: Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: wlines
        path: wlines.exe
