name: Build
on: [push]
jobs:
  build:
    name: Ubuntu->Windows Cross Compile
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v1
    - name: Set up MinGW
      uses: egor-tensin/setup-mingw@v2
      with:
        platform: x64
    - name: Build
      run: make
    - name: Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: wlines
        path: wlines.exe
